version: '3.1'
services:
  stats-server:
    build: ./stats-server
    ports:
      - "8080:8080"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-client:
    build: ./stats-client
    depends_on:
      - stats-server
    ports:
      - "9090:9090"
    environment:
      - STATS_SERVER_URL=http://stats-server:8080

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
