CREATE TABLE IF NOT EXISTS ewm_statistics (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	app varchar(255) NOT NULL,
	ip varchar(255) NOT NULL,
	"time" timestamp NOT NULL,
	uri varchar(255) NOT NULL,
	CONSTRAINT ewm_statistics_pkey PRIMARY KEY (id)
);